//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainGUI.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Role { get; set; }
        public string EmployeeID { get; set; }

        public string DisplayName { get; set; }

        public virtual Employee Employee { get; set; }

        public Account()
        {

        }

        public Account(string username, string password, string role, string emId, string displayName)
        {
            this.UserName = username;
            this.PassWord = password;
            this.Role = role;
            this.EmployeeID = emId;
            this.DisplayName = displayName;
        }
    }
}
