//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainGUI.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee(string employeeId)
        {
            this.Accounts = new HashSet<Account>();
            this.Orders = new HashSet<Order>();
        }

        public Employee(string employeeId, string name, string phone, bool sex, int birth, string address)
        {
            EmployeeID = employeeId;
            Name = name;
            Phone = phone;
            Sex = sex;
            YearOfBirth = birth;
            Address = address;
        }

        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
