//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainGUI.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
      
        public Product()
        {
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product(string text)
        {
            this.OrdersDetails = new HashSet<OrdersDetail>();
            this.ProductsDetails = new HashSet<ProductsDetail>();
        }

        public Product(string text1, string text2, int v1, int v2)
        {
            this.ProductID = text1;
            this.Name = text2;
            this.Quantity = v1;
            this.Price = v2;
        }

        public string ProductID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsDetail> ProductsDetails { get; set; }
    }
}
